export const CYAN = {
    'AQUA/CYAN': '#00FFFF',
    LIGHTCYAN: '#E0FFFF',
    PALETURQUOISE: '#AFEEEE',
    AQUAMARINE: '#7FFFD4',
    TURQUOISE: '#40E0D0',
    MEDIUMTURQUOISE: '#48D1CC',
    DARKTURQUOISE: '#00CED1',
    CADETBLUE: '#5F9EA0',
    LIGHTSEAGREEN: '#20B2AA',
    DARKCYAN: '#008B8B',
    TEAL: '#008080'
};