export const WHITE = {
    WHITE: '#FFFFFF',
    SNOW: '#FFFAFA',
    HONEYDEW: '#F0FFF0',
    MINTCREAM: '#F5FFFA',
    AZURE: '#F0FFFF',
    ALICEBLUE: '#F0F8FF',
    GHOSTWHITE: '#F8F8FF',
    WHITESMOKE: '#F5F5F5',
    SEASHELL: '#FFF5EE',
    BEIGE: '#F5F5DC',
    OLDLACE: '#FDF5E6',
    FLORALWHITE: '#FFFAF0',
    IVORY: '#FFFFF0',
    ANTIQUEWHITE: '#FAEBD7',
    LINEN: '#FAF0E6',
    LAVENDERBLUSH: '#FFF0F5',
    MISTYROSE: '#FFE4E1'
};