export const YELLOW = {
    GOLD: '#FFD700',
    YELLOW: '#FFFF00',
    LIGHTYELLOW: '#FFFFE0',
    LEMONCHIFFON: '#FFFACD',
    LIGHTGOLDENRODYELLOW: '#FAFAD2',
    PAPAYAWHIP: '#FFEFD5',
    MOCCASIN: '#FFE4B5',
    PEACHPUFF: '#FFDAB9',
    PALEGOLDENROD: '#EEE8AA',
    KHAKI: '#F0E68C',
    DARKKHAKI: '#BDB76B'
};